- name: "synch zipped artifact"
  synchronize:
    src: ../../backend
    dest: /home/ubuntu
    recursive: true
- name: "start app"
  shell: |
    cd /tmp/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
